spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  data:
    mongodb:
      port: 27017 # when flapdoodle using should be 0
      database: homework
  batch:
    job:
      enabled: false
  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false

    command:
      version:
        enabled: false
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  runner-type: InitializingBean #when work with spring shell
  change-logs-scan-package:
    - ru.otus.hw.changelog
  mongo-db:
    write-concern:
      journal: true
    read-concern: local
