spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    generate-ddl: false
  h2:
    console:
      enabled: true
      settings:
        trace: true
  cache:
    cache-names:
      - security/acl

logging:
  level:
    org.apache.catalina: DEBUG
    org.springframework.security.acls: DEBUG