spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
